"""Persistence package."""

from ._daemon_models import (
    DaemonFailureCode,
    DaemonFailurePhase,
    DaemonLastRunState,
    DaemonLiveness,
    DaemonNotStartedError,
    DaemonRunMode,
    DaemonStatus,
)
from ._fallback_models import (
    FallbackClaim,
    FallbackFailureCode,
    FallbackNotClaimedError,
    FallbackOutcome,
    FallbackRecord,
)
from ._lazy_sync_lease import InvalidLazySyncLeaseDurationError, LazySyncLease
from ._situation_models import (
    ACTIVE_SITUATION_STATES,
    DeliveryClaim,
    DeliveryConfirmation,
    DeliveryReceiptError,
    DeliveryReservation,
    Detection,
    DetectionApplySummary,
    DetectionUpsertSummary,
    InvalidSituationTransitionError,
    Situation,
    SituationEvidence,
    SituationNotFoundError,
    SituationPriority,
    SituationSource,
    SituationState,
    SituationType,
    SituationValidationError,
)
from ._source_generation import (
    DelayedSourceGenerationError,
    SourceGeneration,
    SourceGenerationState,
    SourceGenerationStatus,
)
from .collectors import (
    DEFAULT_COLLECTOR_STALE_AFTER,
    CollectorProfile,
    CollectorState,
    CollectorStatus,
    CollectorStore,
)
from .daemon_status import DaemonStatusStore, InvalidDaemonPollIntervalError
from .database import (
    DEFAULT_BUSY_TIMEOUT_MS,
    DatabaseStatus,
    Store,
)
from .fallbacks import FallbackStore
from .freshness import (
    DEFAULT_STALE_AFTER,
    SourceFreshness,
    SourceFreshnessStatus,
    evaluate_source_freshness,
)
from .memory import (
    MAX_MEMORY_LEAD_DAYS,
    MAX_MEMORY_PAGE_SIZE,
    Entity,
    EntityAliasConflictError,
    EntityKind,
    EntityStatus,
    FreeDatedMemoryKey,
    MemoryAttribute,
    MemoryItem,
    MemoryKind,
    MemoryNotFoundError,
    MemoryRecurrence,
    MemorySource,
    MemoryValidationError,
    NewMemory,
    free_dated_memory_key,
    normalize_memory_content,
    validate_new_memory,
)
from .private_path import UnsafeDatabasePathError
from .situations import SituationStore
from .storage_errors import ReceiptErasurePendingError
from .sync import (
    SourceAuthState,
    SourceCredentialState,
    SourceErrorCode,
    SourceHealthSnapshot,
    SourceName,
    SourceReadDiagnostics,
    SourceReadReasonCount,
    SourceSyncFailureCode,
    SourceSyncState,
    SyncStore,
)

__all__ = [
    "ACTIVE_SITUATION_STATES",
    "DEFAULT_BUSY_TIMEOUT_MS",
    "DEFAULT_COLLECTOR_STALE_AFTER",
    "DEFAULT_STALE_AFTER",
    "MAX_MEMORY_LEAD_DAYS",
    "MAX_MEMORY_PAGE_SIZE",
    "CollectorProfile",
    "CollectorState",
    "CollectorStatus",
    "CollectorStore",
    "DaemonFailureCode",
    "DaemonFailurePhase",
    "DaemonLastRunState",
    "DaemonLiveness",
    "DaemonNotStartedError",
    "DaemonRunMode",
    "DaemonStatus",
    "DaemonStatusStore",
    "DatabaseStatus",
    "DelayedSourceGenerationError",
    "DeliveryClaim",
    "DeliveryConfirmation",
    "DeliveryReceiptError",
    "DeliveryReservation",
    "Detection",
    "DetectionApplySummary",
    "DetectionUpsertSummary",
    "Entity",
    "EntityAliasConflictError",
    "EntityKind",
    "EntityStatus",
    "FallbackClaim",
    "FallbackFailureCode",
    "FallbackNotClaimedError",
    "FallbackOutcome",
    "FallbackRecord",
    "FallbackStore",
    "FreeDatedMemoryKey",
    "InvalidDaemonPollIntervalError",
    "InvalidLazySyncLeaseDurationError",
    "InvalidSituationTransitionError",
    "LazySyncLease",
    "MemoryAttribute",
    "MemoryItem",
    "MemoryKind",
    "MemoryNotFoundError",
    "MemoryRecurrence",
    "MemorySource",
    "MemoryValidationError",
    "NewMemory",
    "ReceiptErasurePendingError",
    "Situation",
    "SituationEvidence",
    "SituationNotFoundError",
    "SituationPriority",
    "SituationSource",
    "SituationState",
    "SituationStore",
    "SituationType",
    "SituationValidationError",
    "SourceAuthState",
    "SourceCredentialState",
    "SourceErrorCode",
    "SourceFreshness",
    "SourceFreshnessStatus",
    "SourceGeneration",
    "SourceGenerationState",
    "SourceGenerationStatus",
    "SourceHealthSnapshot",
    "SourceName",
    "SourceReadDiagnostics",
    "SourceReadReasonCount",
    "SourceSyncFailureCode",
    "SourceSyncState",
    "Store",
    "SyncStore",
    "UnsafeDatabasePathError",
    "evaluate_source_freshness",
    "free_dated_memory_key",
    "normalize_memory_content",
    "validate_new_memory",
]
